let usedPrompts = [];

document.addEventListener("DOMContentLoaded", () => {
    document.getElementById("generateBtn").addEventListener("click", () => {
        const selectedList = document.getElementById("promptList").value;
        const availablePrompts = prompts[selectedList].filter(prompt => !usedPrompts.includes(prompt));

        if (availablePrompts.length === 0) {
            document.getElementById("prompt").innerText = "No more prompts available in this list.";
            return;
        }

        const randomIndex = Math.floor(Math.random() * availablePrompts.length);
        const randomPrompt = availablePrompts[randomIndex];

        usedPrompts.push(randomPrompt);
        document.getElementById("prompt").innerText = randomPrompt;

        const recentPromptsList = document.getElementById("recent-prompts");
        const listItem = document.createElement("li");
        listItem.innerText = randomPrompt;
        recentPromptsList.appendChild(listItem);
    });
});

const prompts = {
    list1: [
        "eden",
        "supernova",
        "sleepwalk",
        "name",
        "ribbon",
        "clocks",
        "biology",
        "gray",
        "stars",
        "kalediscope",
        "anachronism",
        "piano",
        "everything",
        "shimmer",
        "reason",
        "fact",
        "rhapsody",
        "old",
        "lucid",
        "asymmetry",
        "family",
        "white",
        "sky",
        "adventure",
        "flavors",
        "silence",
        "shades",
        "faces",
        "energy",
        "voice",
        "love",
        "optimism",
        "release",
        "breath",
        "shiver",
        "lonely",
        "balance",
        "collection",
        "mosaic",
        "grasp"
    ],
    list2: [
        "the things I should have said",
        "I wanna be free",
        "the weight of the world",
        "up so high",
        "on the nightstand",
        "if you wanted honesty...",
        "next to mine",
        "if you want me to",
        "the sea",
        "emotions arise",
        "never let you go",
        "spinning",
        "so I ran faster",
        "i need to know",
        "sweet and divine",
        "hanging from a cliff",
        "where were you?",
        "stepping stones",
        "I won't let you fall apart",
        "time after time",
        "blinded by the light",
        "a broken circle",
        "the dark night of the soul",
        "my days are the highway kind",
        "this is what it means to sing the blues",
        "night, and the loves of...",
        "one song glory",
        "the ghost haunting through your heart",
        "I laughed so hard, I nearly cried",
        "love is for the fools who fall behind",
        "the chimera obscurant",
        "you are the last line drawn in the sand",
        "half accidental, half painful instrumental",
        "history repeats",
        "never seen a bluer sky",
        "defying gravity",
        "all these pieces of you",
        "under the glass moon",
        "echoes in winter",
        "fumbling towards ecstacy",
        ],
    list3: [
        "Scream",
        "Whimper",
        "Wail",
        "Sob",
        "Cough",
        "Sneeze",
        "Yawn",
        "Gasp",
        "Hiccup",
        "Belch",
        "Groan",
        "Moan",
        "Cry",
        "Growl",
        "Grunt",
        "Laugh",
        "Squeal",
        "Hum",
        "Sigh",
        "Snore",
        "Gurgle",
        "Pant",
        "Chew",
        "Talk",
        "Slurp",
    ],
    list4: [
        "Feet",
        "Bicycle",
        "Motorcycle",
        "Car",
        "Bus",
        "Subway",
        "Train",
        "Airplane",
        "Ferry",
        "Cruise Ship",
        "Spaceship"
      ],
    list5: [
        "The Beach",
        "The Mountains",
        "A River",
        "The Ocean",
        "A Lake",
        "A Field",
        "A Meadow",
        "A Forest",
        "The Woods",
        "The Jungle",
        "A Valley",
        "A Plain",
        "A Volcano",
        "A Waterfall",
        "A Canyon",
        "The Rainforest",
        "A Cliff",
        "A Pond",
        "A Whirlpool",
        "A Cave",
        "A Glacier",
        "A Marsh",
    ],
    list6: [
        "Crimes",
        "Murder",
        "Assisted suicide",
        "Kidnap",
        "Robbery",
        "Rape",
        "Sexual abuse",
        "Physical abuse",
        "Child abuse",
        "Assault and battery",
        "Drug smuggling",
        "Drug dealing",
        "Driving while intoxicated",
        "Drug buying",
        "Attempted murder",
        "Money laundering",
        "Accomplicing",
        "Attempted suicide",
        "Violating probation",
        "Tresspassing",
        "Vandalism",
        "Computer hacking",
        "Harassment",
        "Arson",
        "Cruelty to animals",
    ],
    list7: [
        "Sunshine",
        "Candle",
        "Fire",
        "Lightbulb",
        "Torch",
        "Flashlight",
        "Moonlight",
        "Fireflies",
        "Lightning",
        "Lightning bug",
        "Lantern",
        "Lamp",
        "Starlight",
        "Headlights",
        "Tail lights",
        "Black light",
        "TV",
        "Computer",
        "Microwave",
        "Electricity",
    ],
    list8: [
        "Red",
        "Orange",
        "Yellow",
        "Green",
        "Blue",
        "Violet",
        "Brown",
        "Black",
        "White",
        "Grey",
    ]
      
};